spring.application.name=rms-api
spring.datasource.url=jdbc:postgresql://ep-hidden-waterfall-aoz55jvw-pooler.c-2.ap-southeast-1.aws.neon.tech/rms?user=admin&password=npg_5VGolHKyp8iJ&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
